### ISSUE TITLE
Mentioning divergent features

### ISSUE THREAD

**Issue by workingj** [omentic/helix-ext#47]
Hi there :>,
would you mind mentioning the features that diverge from helix in the readme, or somewhere else in the repo :smile:

**Comment by omentic** [comment]
They are mentioned here: https://github.com/omentic/helix-ext/commits/master/

**Comment by omentic** [comment]
Ah, here is probably a more detailed list. I suppose both link to the original works though.
https://github.com/omentic/helix-ext/releases
